version: '3'

services:

  ontology:
    
    image: kerxd/ontology-app:latest

    container_name: docker-ontology

    environment:
      - SERVER_PORT=80

    ports:
      - "88:80"

    networks: 
      - ontology-network


  drae:

    image: squat/drae:latest

    container_name: docker-squat-drae

    environment:
      - SERVER_PORT=4000

    ports:
      - "4000:4000"

    networks:
      - ontology-network


networks:
  ontology-network: