version: '3'

services:

  ontology:
    
    image: kerxd/ontology-app:latest

    container_name: docker-ontology

    ports:
      - "88:88"

    networks:
      - ontology-network

    depends_on:
      - mysqldb



  mysqldb:

    image: mysql:8

    container_name: docker-mysql-user

    networks:
      - ontology-network

    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=user_details

    volumes:
      - mysql_db:/var/lib/mysql


volumes:
  mysql_db:

networks:
  ontology-network: