version: '3'

services:

  ontology:
    
    image: kerxd/ontology-app:latest

    container_name: docker-ontology

    environment:
      - SERVER_PORT=88

    ports:
      - "88:88"

    networks:
      - ontology-network

    depends_on:
      - drae

  drae:

    image: squat/drae:latest

    container_name: docker-squat-drae

    environment:
      - SERVER_PORT=4000

    ports:
      - "4000:4000"

    networks:
      - ontology-network


networks:
  ontology-network: