# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Continous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle And Skipping test
      run: ./gradlew build -x test
      
    - name: Build Jar With BootJar
      run: ./gradlew bootJar
      
    - name: Docker Login 
#     Setting secrets to enviroment variables
      env: 
        DOCKER_USER: ${{ secrets.DOCKER_USER }} 
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} 
      
#       Login in docker hub with my enviroment variable
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      
#       Aqui creo la imagen y le hago push
    - name: Build Docker Image
      run: docker build -t kerxd/ontology-app .

#      Desactivado hasta que automatice la conexion entre la ontologia y la app
#    - name: Push Docker Image
#      run: docker push kerxd/ontology-app
      
      
