name: Continous Integration Continous Deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11

        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

# -x test para desactivar las pruebas unitarias a la hora de subi con docker
      - name: Build and test with Gradle
        run: ./gradlew build

#Si no deseo subir imagen de docker comentare los sigtes jobs
#    - name: Build Jar With Gradle
#      run: ./gradlew bootJar

#      # Setting secrets to environment variables To login in docker
#    - name: Login To Docker
#      env:
#        DOCKER_USER: ${{ secrets.DOCKER_USER }}
#        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#
##       Login in docker hub with my environment variable
#      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
#
##       Build docker image and then push the image to dockerhub
#    - name: Build Docker Image
#      run: docker build -t kerxd/ontology-app .
#
#    - name: Push Docker Image
#      run: docker push kerxd/ontology-app

      
      
